#  Actions Tab에 나타날 name (필수 아님)
name: CI_node

# Workflow Event list
# 브랜치 구분 없이 하려면 on: [push, pull_request]
on: [push]

# User가 수동으로 Actions Tab에서 workflow 실행    
# workflow_dispatch:
jobs:
  # CI
  build:
    # Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm i

      - name: Test npm
        run: npm test
      
      - name: Remove node_modules
        run: rm -rf ./node_modules

      - name: Upload files
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "./*"  # 로컬에서 빌드한 파일들
          target: "~/project"  # 서버에 업로드할 경로

      - name: Deploy server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ~/project            
            npm install
            nohup npm start >> test.log &